spring.application.name=VeterinariaH

spring.datasource.url=jdbc:postgresql://localhost:5432/veterinaria
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
jwt.secret=VeterinariaHClaveSecretaSuperSeguraParaJWT2026
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
