-- ============================================
-- BASE DE DATOS: SISTEMA DE GESTIÓN VETERINARIA
-- MIGRACIÓN INICIAL
-- ============================================


-- ============================================
-- TABLA CLIENTE
-- ============================================

CREATE TABLE cliente (

    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,

    telefono VARCHAR(30),
    email VARCHAR(150),

    direccion VARCHAR(255)

);


-- ============================================
-- TABLA MASCOTA
-- ============================================

CREATE TABLE mascota (

    id_mascota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_cliente BIGINT NOT NULL,

    nombre VARCHAR(100) NOT NULL,

    especie VARCHAR(100) NOT NULL,
    raza VARCHAR(100),

    peso NUMERIC(10,2),

    tipo_pelo VARCHAR(100),

    fecha_nacimiento DATE,

    CONSTRAINT fk_mascota_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)

);


-- ============================================
-- TABLA SERVICIO
-- ============================================

CREATE TABLE servicio (

    id_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    descripcion VARCHAR(500),

    tipo VARCHAR(100),

    precio_base NUMERIC(12,2) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE

);


-- ============================================
-- TABLA PAQUETE
-- ============================================

CREATE TABLE paquete (

    id_paquete BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    descripcion VARCHAR(500),

    precio NUMERIC(12,2) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE

);


-- ============================================
-- TABLA PRODUCTO
-- ============================================

CREATE TABLE producto (

    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    descripcion VARCHAR(500),

    stock_actual NUMERIC(12,2) NOT NULL DEFAULT 0,

    stock_minimo NUMERIC(12,2) NOT NULL DEFAULT 0,

    unidad_medida VARCHAR(50) NOT NULL,

    contenido_por_unidad NUMERIC(12,2),

    activo BOOLEAN NOT NULL DEFAULT TRUE

);


-- ============================================
-- TABLA TARIFA_SERVICIO
-- ============================================

CREATE TABLE tarifa_servicio (

    id_tarifa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_servicio BIGINT NOT NULL,

    especie VARCHAR(100),

    raza VARCHAR(100),

    tamano VARCHAR(50),

    tipo_pelo VARCHAR(100),

    precio NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_tarifa_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio)

);


-- ============================================
-- TABLA PAQUETE_SERVICIO
-- Relación entre PAQUETE y SERVICIO
-- ============================================

CREATE TABLE paquete_servicio (

    id_paquete_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_paquete BIGINT NOT NULL,

    id_servicio BIGINT NOT NULL,

    CONSTRAINT fk_paquete_servicio_paquete
        FOREIGN KEY (id_paquete)
        REFERENCES paquete(id_paquete),

    CONSTRAINT fk_paquete_servicio_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio)

);


-- ============================================
-- TABLA PRODUCTO_SERVICIO
-- Relación entre PRODUCTO y SERVICIO
-- ============================================

CREATE TABLE producto_servicio (

    id_producto_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_servicio BIGINT NOT NULL,

    id_producto BIGINT NOT NULL,

    dosis_por_kg NUMERIC(12,2),

    unidad_medida VARCHAR(50),

    CONSTRAINT fk_producto_servicio_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio),

    CONSTRAINT fk_producto_servicio_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)

);


-- ============================================
-- TABLA VENTA
-- ============================================

CREATE TABLE venta (

    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_cliente BIGINT NOT NULL,

    id_mascota BIGINT,

    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    total NUMERIC(12,2) NOT NULL DEFAULT 0,

    metodo_pago VARCHAR(50) NOT NULL,

    estado VARCHAR(50) NOT NULL,

    es_domicilio BOOLEAN NOT NULL DEFAULT FALSE,

    direccion_domicilio VARCHAR(255),

    costo_domicilio NUMERIC(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_venta_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente),

    CONSTRAINT fk_venta_mascota
        FOREIGN KEY (id_mascota)
        REFERENCES mascota(id_mascota)

);


-- ============================================
-- TABLA DETALLE_VENTA_SERVICIO
-- ============================================

CREATE TABLE detalle_venta_servicio (

    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_venta BIGINT NOT NULL,

    id_servicio BIGINT NOT NULL,

    precio NUMERIC(12,2) NOT NULL,

    cantidad INTEGER NOT NULL DEFAULT 1,

    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_detalle_venta_servicio_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),

    CONSTRAINT fk_detalle_venta_servicio_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES servicio(id_servicio)

);


-- ============================================
-- TABLA DETALLE_VENTA_PAQUETE
-- ============================================

CREATE TABLE detalle_venta_paquete (

    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_venta BIGINT NOT NULL,

    id_paquete BIGINT NOT NULL,

    precio NUMERIC(12,2) NOT NULL,

    cantidad INTEGER NOT NULL DEFAULT 1,

    subtotal NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_detalle_venta_paquete_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta),

    CONSTRAINT fk_detalle_venta_paquete_paquete
        FOREIGN KEY (id_paquete)
        REFERENCES paquete(id_paquete)

);


-- ============================================
-- TABLA CONSUMO_PRODUCTO
-- ============================================

CREATE TABLE consumo_producto (

    id_consumo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_producto BIGINT NOT NULL,

    id_venta BIGINT NOT NULL,

    cantidad_utilizada NUMERIC(12,2) NOT NULL,

    unidad_medida VARCHAR(50) NOT NULL,

    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_consumo_producto_producto
        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto),

    CONSTRAINT fk_consumo_producto_venta
        FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta)

);